In [2]:
from skimage.io import imread
import pandas as pd
import numpy as np
import skimage
import pylab
from sklearn.cluster import KMeans

image = imread('parrots.jpg')

float_data = skimage.img_as_float(image)
w, h, d = float_data.shape
float_data = np.reshape(a=float_data, newshape=(w * h, d))
data = pd.DataFrame(data=float_data, columns=['R', 'G', 'B'])

kmean = KMeans(init='k-means++', random_state=241)
cluster = kmean.fit_predict(data)
data['cluster'] = cluster

means = data.groupby('cluster', as_index=False).mean()
median = data.groupby('cluster', as_index=False).median()

# mean_data = means.iloc[data['cluster'], :]
# mean_data = mean_data[['R', 'G', 'B']]  # cut off cluster
# 
# median_data = median.iloc[data['cluster'], :]
# median_data = median_data[['R', 'G', 'B']]  # cut off cluster
# 


In [22]:
means = data.groupby('cluster').mean().values
mean_pixels = [means[c] for c in data['cluster'].values]
mean_image = np.reshape(mean_pixels, (w, h, d))


[array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.06691699]),
 array([0.09564693, 0.63556673, 0.

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>R</th>
      <th>G</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.095647</td>
      <td>0.635567</td>
      <td>0.066917</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>0</th>
      <td>0.053985</td>
      <td>0.116691</td>
      <td>0.050403</td>
    </tr>
    <tr>
      <th>0</th>
      <td>0.053985</td>
      <td>0.116691</td>
      <td>0.050403</td>
    </tr>
    <tr>
      <th>0</th>
      <